//! The generated-file header.
//!
//! Every rendered overlay begins with a machine-readable marker line carrying
//! the context hash (so `refresh` can detect "nothing changed"), a human block
//! describing provenance, and a visible warning that the file is generated and
//! is **guidance, not policy**.

/// Prefix of the machine-readable first line of every generated file.
pub const GENERATED_MARKER: &str = "<!-- loadout:generated";

/// Metadata rendered into the header.
pub struct HeaderMeta<'a> {
    /// RFC3339 generation timestamp.
    pub generated_at: &'a str,
    /// Host the snapshot was generated on.
    pub host: &'a str,
    /// Agent id (`claude`/`codex`/`gemini`/…).
    pub agent: &'a str,
    /// Selected profile name.
    pub profile: &'a str,
    /// `sha256:…` context hash.
    pub context_hash: &'a str,
    /// Where the base template came from.
    pub template_source: &'a str,
    /// Config files that contributed (display strings).
    pub sources: &'a [String],
    /// Count of `Pending` learn candidates awaiting review in the inbox
    /// (`0` when `[learn]` is disabled or nothing is staged). Purely
    /// decorative, like `host`/`generated_at`: it is NOT folded into the
    /// context hash (the caller computes it independently and passes it in
    /// after the hash is already final — see `render::render`), so a change
    /// in pending count alone never churns the hash or forces a rewrite. The
    /// trade this accepts, matching `host`/`generated_at`'s existing
    /// staleness: under the hash-skip, this line only reaches the on-disk
    /// file the next time something ELSE causes a real re-render (or
    /// `--force`) — the live count is the `run` step line and the `refresh`
    /// summary line, both printed fresh on every invocation.
    pub pending_learn: usize,
}

/// Build the full header block (ends with a trailing blank line).
///
/// Includes a **self-healing** banner: it tells the agent when/where the
/// snapshot was made and the exact commands to verify, refresh, or remove it —
/// plus the `$LOADOUT_RUN` signal so an agent launched via `load run` knows the
/// context is current, and one launched directly knows to check freshness.
pub fn build(meta: &HeaderMeta) -> String {
    let sources = if meta.sources.is_empty() {
        "(built-in defaults only)".to_string()
    } else {
        meta.sources.join(", ")
    };
    // The learn discovery line: at most one, present only when there's
    // something to review. Deliberately built as a separate blockquote
    // paragraph (its own `> \n> …`) rather than appended onto the self-heal
    // line, so it reads as a distinct notice.
    let learn_line = if meta.pending_learn > 0 {
        format!(
            "> \n\
             > loadout: {n} staged suggestions await review — load studio\n",
            n = meta.pending_learn,
        )
    } else {
        String::new()
    };
    format!(
        "{GENERATED_MARKER} context={hash} -->\n\
         <!--\n\
         \x20 GENERATED BY loadout — DO NOT EDIT BY HAND.\n\
         \x20 generated : {generated_at}\n\
         \x20 host      : {host}\n\
         \x20 agent     : {agent}\n\
         \x20 profile   : {profile}\n\
         \x20 context   : {hash}\n\
         \x20 template  : {template}\n\
         \x20 sources   : {sources}\n\
         -->\n\
         \n\
         > **What is loadout?** loadout is a tool the user runs to inject their personal, global \
         context — their standing conventions and preferences — into AI coding agents like you. \
         The guidance below comes from the user and applies across their projects; it is not this \
         repository's own policy.\n\
         > \n\
         > 🕒 loadout snapshot — **{host}**, **{generated_at}**, profile **{profile}** (context {hash}).\n\
         > This is point-in-time **agent guidance, not enforced policy**, and may be stale.\n\
         > Check freshness with `load doctor`; regenerate with `load refresh`; remove with `load clean`.\n\
         > If `$LOADOUT_RUN` is unset, run `load refresh` before relying on this (it skips work when \
         nothing changed), then re-read this file.\n\
         {learn_line}\
         \n",
        hash = meta.context_hash,
        generated_at = meta.generated_at,
        host = meta.host,
        agent = meta.agent,
        profile = meta.profile,
        template = meta.template_source,
        sources = sources,
        learn_line = learn_line,
    )
}

/// Extract the `context=sha256:…` hash from a previously generated file, if any.
///
/// Returns the **last** marker found, not the first. A lone generated file has a
/// single marker (first == last), but when the overlay is inlined into a larger
/// user-owned file (e.g. the Codex `AGENTS.override.md`) the managed block is
/// appended *after* the base content — so if that base happens to carry its own
/// stray loadout marker, the last one is reliably the managed block's.
pub fn extract_context_hash(content: &str) -> Option<String> {
    let mut last = None;
    for line in content.lines() {
        let Some(rest) = line.trim_start().strip_prefix(GENERATED_MARKER) else {
            continue;
        };
        let Some(token) = rest.trim_start().strip_prefix("context=") else {
            continue;
        };
        let hash: String = token.chars().take_while(|c| !c.is_whitespace()).collect();
        if !hash.is_empty() {
            last = Some(hash);
        }
    }
    last
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> String {
        sample_with_pending(0)
    }

    fn sample_with_pending(pending_learn: usize) -> String {
        build(&HeaderMeta {
            generated_at: "2026-05-29T13:35:56Z",
            host: "mac-air",
            agent: "claude",
            profile: "rust",
            context_hash: "sha256:abcdef1234567890",
            template_source: "embedded",
            sources: &[".loadout/config.toml".to_string()],
            pending_learn,
        })
    }

    #[test]
    fn header_contains_fields_and_self_healing_banner() {
        let h = sample();
        assert!(h.starts_with(GENERATED_MARKER));
        assert!(h.contains("profile   : rust"));
        assert!(h.contains("agent     : claude"));
        assert!(h.contains("host      : mac-air"));
        assert!(h.contains("DO NOT EDIT"));
        assert!(h.contains("not enforced policy"));
        // explains what loadout is so the agent can make sense of the context,
        // addressed to the agent and attributing the guidance to the user
        assert!(h.contains("What is loadout?"));
        assert!(h.contains("comes from the user"));
        // self-healing instructions + launch-mode signal: an agent launched
        // outside `load run` is told to *run* the refresh itself, not merely
        // that it could.
        assert!(h.contains("load refresh"));
        assert!(h.contains("load clean"));
        assert!(h.contains("run `load refresh` before relying on this"));
        assert!(h.contains("then re-read this file"));
        assert!(h.contains("$LOADOUT_RUN"));
    }

    #[test]
    fn roundtrips_context_hash() {
        let h = sample();
        assert_eq!(
            extract_context_hash(&h).as_deref(),
            Some("sha256:abcdef1234567890")
        );
    }

    #[test]
    fn no_hash_when_absent() {
        assert_eq!(extract_context_hash("# just a file\n"), None);
        assert_eq!(extract_context_hash(""), None);
    }

    #[test]
    fn no_learn_line_when_pending_is_zero() {
        let h = sample_with_pending(0);
        assert!(!h.contains("staged suggestions"));
        assert!(!h.contains("load studio"));
    }

    #[test]
    fn learn_line_present_and_exact_when_pending_is_nonzero() {
        let h = sample_with_pending(3);
        assert!(h.contains("> loadout: 3 staged suggestions await review — load studio\n"));
    }

    #[test]
    fn learn_line_does_not_disturb_the_rest_of_the_header() {
        // Everything else in the header (banner, self-heal instructions,
        // provenance fields) must be unaffected by whether the learn line is
        // present — the two headers should differ ONLY in that line.
        let without = sample_with_pending(0);
        let with = sample_with_pending(5);
        assert_ne!(without, with);
        // Splicing the exact learn-line snippet back out of `with` must
        // reproduce `without` byte-for-byte — i.e. those are the ONLY two
        // lines the pending count added.
        let learn_snippet = "> \n> loadout: 5 staged suggestions await review — load studio\n";
        assert_eq!(with.replacen(learn_snippet, "", 1), without);
    }

    #[test]
    fn picks_last_marker_when_base_has_a_stray_one() {
        // Mimics an override file whose base content carries a stray loadout
        // marker before the appended managed block: the managed block's hash
        // (last) must win, so freshness tracks the right thing.
        let content = format!(
            "{GENERATED_MARKER} context=sha256:stale -->\nbase content\n\
             <!-- BEGIN loadout (managed) -->\n\
             {GENERATED_MARKER} context=sha256:fresh -->\noverlay\n\
             <!-- END loadout (managed) -->\n"
        );
        assert_eq!(
            extract_context_hash(&content).as_deref(),
            Some("sha256:fresh")
        );
    }
}
